### ISSUE TITLE
I need help with kheops

### ISSUE THREAD

**Issue by kleber011** [hirsch-lab/kheops-client#1]
My email and WhatsApp

batistakleber9@gmail.com

WhatsApp +5511983684316

**Comment by normanius** [comment]
I'm not a Kheops expert myself. You got in touch with the Kheops developers in the meanwhile, so I close this issue here.

Quite uncommon to share phone numbers on github. Also, this is an issue tracking system, not a social platform. Please address particular problems, and not generic "I need help" requests. Thanks.

**Comment by kleber011** [comment]
I have logs here you can help me

Em sex, 26 de ago de 2022 09:02, normanius ***@***.***>
escreveu:
